require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/parking_spaces", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ParkingSpace. As you add validations to ParkingSpace, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ParkingSpace.create! valid_attributes
      get parking_spaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parking_space = ParkingSpace.create! valid_attributes
      get parking_space_url(parking_space)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parking_space_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      parking_space = ParkingSpace.create! valid_attributes
      get edit_parking_space_url(parking_space)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ParkingSpace" do
        expect {
          post parking_spaces_url, params: { parking_space: valid_attributes }
        }.to change(ParkingSpace, :count).by(1)
      end

      it "redirects to the created parking_space" do
        post parking_spaces_url, params: { parking_space: valid_attributes }
        expect(response).to redirect_to(parking_space_url(ParkingSpace.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ParkingSpace" do
        expect {
          post parking_spaces_url, params: { parking_space: invalid_attributes }
        }.to change(ParkingSpace, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post parking_spaces_url, params: { parking_space: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parking_space" do
        parking_space = ParkingSpace.create! valid_attributes
        patch parking_space_url(parking_space), params: { parking_space: new_attributes }
        parking_space.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parking_space" do
        parking_space = ParkingSpace.create! valid_attributes
        patch parking_space_url(parking_space), params: { parking_space: new_attributes }
        parking_space.reload
        expect(response).to redirect_to(parking_space_url(parking_space))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        parking_space = ParkingSpace.create! valid_attributes
        patch parking_space_url(parking_space), params: { parking_space: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parking_space" do
      parking_space = ParkingSpace.create! valid_attributes
      expect {
        delete parking_space_url(parking_space)
      }.to change(ParkingSpace, :count).by(-1)
    end

    it "redirects to the parking_spaces list" do
      parking_space = ParkingSpace.create! valid_attributes
      delete parking_space_url(parking_space)
      expect(response).to redirect_to(parking_spaces_url)
    end
  end
end
